### ISSUE TITLE
[feature req] Enable a class instantiation from an Hjson file

### ISSUE THREAD

**Issue by tbrowder** [vrurg/raku-JSON-Class#1]
See raku module 'JSON::Hjson'.

I may be able to do that on my end, but I haven't yet grokked how to get a single class instance from a JSON string or data file with this module. I am actively experimenting now...

**Comment by vrurg** [comment]
> See raku module 'JSON::Hjson'.

Isn't JSONC the same thing? `JSON::Fast` supports it, `JSON::Class::Config` has `allow-jsonc` parameter. Otherwise support for another backend would be required. I don't do my own parsing. Not yet, at least.

> but I haven't yet grokked how to get a single class instance from a JSON string or data file with this module

What do you mean? Why

```raku
class Mine is json {...}
Mine.from-json($json-string)
```

isn't what you need?

**Comment by tbrowder** [comment]
I said I was still experimenting, but thanks for the pointer. That's a **LOT** of documentation.

As far as I've been able to tell, Hjson and JSONC are technically not the same. They have two different websites, and Hjson's is more "official" looking.

I just confirmed with the Hjson site: the two are not the same.

**Comment by vrurg** [comment]
Then for Hjson support it is better, perhaps, to make it available via `JSON::Fast`.

**Comment by tbrowder** [comment]
Yes. But my problem now is when trying to install this module, my host hangs when installing dep Test::Async. It's hanging on two hosts, one with 96 Gb of memory and 32 cores.

**Comment by vrurg** [comment]
My guess would be that it hangs in a test. Would be possible for you to clone Test::Async repo and try to find out which particular test hangs?

**Comment by tbrowder** [comment]
Overcome by events
